name: cicd_prdt

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

on: [workflow_dispatch]

env:
  PROJECT_NAME: babify
  AWS_REGION: ap-northeast-2
  S3_BUCKET: jw-cicd
#  S3_FOLDER: adsrun-v2-prdt
  CODE_DEPLOY_APPLICATION_NAME: jw-babify
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: jw-babify-prdt

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    # (1) 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v4

    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

   
